# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  - main

parameters:
  - name: numThreadToken
    displayName: NUMBER_THREAD_TOKEN
    default: 1
    type: string
  
  - name: rampUpPeriodToken
    displayName: RAMP_UP_PERIOD_TOKEN
    default: 1
    type: string
  
  - name: loopCount
    displayName: LOOP_COUNT
    default: 1
    type: string
  
  - name: loopToken
    displayName: LOOP_TOKEN
    default: 1
    type: string
    
  - name: numThreads
    displayName: NUM_THREADS
    default: 10
    type: string

  - name: rampUpPeriod
    displayName: RAMP_UP_PERIOD
    default: 20
    type: string

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test -DnumThreadToken=${{parameters.numThreadToken}} -DrampUpPeriodToken=${{parameters.rampUpPeriodToken}} -DloopToken=${{parameters.loopToken}} -DloopCount=${{parameters.loopCount}} -DnumThreads=${{parameters.numThreads}} -DrampUpPeriod=${{parameters.rampUpPeriod}} verify'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
  continueOnError: true
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  inputs:
      PathtoPublish: 'target/jmeter/results'
      ArtifactName: 'Reports'
      publishLocation: 'Container'
  continueOnError: true
  condition: succeededOrFailed()