trigger:
  - main

parameters:
  - name: numThreads
    displayName: THREADS
    default: 10
    type: string
  
  - name: rampUpPeriod
    displayName: RAMP_UP
    default: 10
    type: string
  
  - name: loopCount
    displayName: LOOP_COUNT
    default: 10
    type: string

steps:
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test -DnumThreads=${{parameters.numThreads}} -DrampUpPeriod=${{parameters.rampUpPeriod}} -DloopCount=${{parameters.loopCount}} verify'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  continueOnError: true
  condition: always()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Report'
  inputs:
    PathtoPublish: 'target/jmeter/results'
    ArtifactName: Report
  condition: always()